version: "3.1"
services:
  app:
    container_name: ticket-project
    image: ticket-project/node
    ports:
      - "3000:3000"
    build: .
    volumes:
      - ./server/src:/app/server/src
    networks:
      - ticket-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ticket-network
volumes:
  mysql-data:
networks:
  ticket-network:
